---
apiVersion: v1
kind: Namespace
metadata:
  name: myapp
---
# Grant the kube-system/tiller SA cluster-admin at the cluster scope
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: developer
  namespace: myapp
  creationTimestamp: null
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: User
    name: demo@example.com
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: default-deny-all
  namespace: myapp
spec:
  podSelector: {}
  egress: []
  ingress: []
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-default-egress
  namespace: myapp
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
